apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Leomendoza13/eks-scalable-devops-platform
    path: kubernetes/overlays/dev/monitoring/prometheus
    targetRevision: readmev2
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true