apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KHDevOps/eks-scalable-devops-platform
    path: helm-charts/jenkins
    targetRevision: monitoring
    helm:
      valueFiles:
        - ../../helm-values/dev/jenkins/values.yaml
      skipCrds: false 
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true