apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Leomendoza13/eks-scalable-devops-platform
    path: helm-charts/prometheus
    targetRevision: aws
    helm:
      valueFiles:
        - ../../kustomize/overlays/dev/prometheus/values.yaml
      skipCrds: false 
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=false
    - ServerSideApply=true