controller:
  admissionWebhooks:
    enabled: false
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 101
    capabilities:
      drop:
        - ALL
      add:
        - NET_BIND_SERVICE

  podSecurityContext:
    fsGroup: 101

  resources:
    requests:
      cpu: 100m
      memory: 190Mi
    limits:
      cpu: 200m
      memory: 250Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  service:
    type: NodePort
    nodePorts:
      http: 31142
      https: 31080
  config:
    ssl-redirect: "false"
  extraArgs:
    enable-ssl-passthrough: "false"