# Single node setup for Minikube
singleNode: true
replicas: 1

# Set the initial admin password (THIS IS WHERE IT GOES!)
extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "Test123!!@Sfdsaslkcm?"

# Very small resources for Minikube
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"