# Single node setup for Minikube
singleNode: true
replicas: 1

# Disable security completely for testing
extraEnvs:
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"

# Very small resources for Minikube
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

# Disable security plugin
config:
  opensearch.yml: |
    plugins.security.disabled: true
    discovery.type: single-node

# Use hostPath for persistence (Minikube friendly)
persistence:
  enabled: false