# helm-values/dev/opensearch/values.yaml

# Single node for development
singleNode: true
replicas: 1

# Set environment variables (try different syntax)
env:
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: " "

# Also try extraEnvs (in case the chart uses this)
extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "MyStrongPassword123!"

# Increased resources for OpenSearch
resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"

# Disable security for simplicity  
config:
  opensearch.yml: |
    plugins.security.disabled: true
    discovery.type: single-node
    
# Set admin password in environment
opensearchEnv:
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: "MyStrongPassword123!"