# OpenSearch - Fixed values.yaml for version 3.0.0
replicas: 1

# CRITICAL: Admin password for OpenSearch 3.0.0+
extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "MyPassword123!"

# Minimal resources
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

# Simplified configuration - let the demo installer handle security setup
config:
  opensearch.yml: |
    discovery.type: single-node
    
# No persistence for testing
persistence:
  enabled: false

# Simple service
service:
  type: ClusterIP

# Explicitly set single node
singleNode: true

# Allow the demo configuration to run
securityConfig:
  enabled: false