# OpenSearch - Simple Minikube values.yaml
replicas: 1
minimumMasterNodes: 1

# Simple password
extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "MyPassword123!"
  - name: "DISABLE_INSTALL_DEMO_CONFIG"
    value: "true"

# Minimal resources
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

# Disable security for simplicity
config:
  opensearch.yml: |
    plugins.security.disabled: true
    discovery.type: single-node

# No persistence for testing
persistence:
  enabled: false

# Simple service
service:
  type: ClusterIP