# OpenSearch - Updated values.yaml with security enabled
replicas: 1

# Admin password
extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "MyPassword123!"

# Minimal resources
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

# Enable security but use basic configuration
config:
  opensearch.yml: |
    # Enable security plugin
    plugins.security.disabled: false
    
    # Single node setup
    discovery.type: single-node
    
    # Basic security settings for development
    plugins.security.ssl.transport.enabled: false
    plugins.security.ssl.http.enabled: false
    plugins.security.allow_default_init_securityindex: true
    plugins.security.authcz.admin_dn:
      - "CN=admin,O=client,L=test,C=de"
    plugins.security.nodes_dn:
      - "CN=node.example.com,O=node,L=test,C=de"
    plugins.security.audit.type: internal_opensearch
    plugins.security.enable_snapshot_restore_privilege: true
    plugins.security.check_snapshot_restore_write_privileges: true
    plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]

# No persistence for testing
persistence:
  enabled: false

# Simple service
service:
  type: ClusterIP

# Explicitly set single node
singleNode: true