# Single node setup for Minikube
singleNode: true
replicas: 1

# Set the initial admin password (THIS IS WHERE IT GOES!)
extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "Admin123!"

# Very small resources for Minikube
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

# Enable security with demo certs
config:
  opensearch.yml: |
    plugins.security.disabled: false
    plugins.security.allow_default_init_securityindex: true
    plugins.security.allow_unsafe_democertificates: true
    discovery.type: single-node

# Use hostPath for persistence (Minikube friendly)
persistence:
  enabled: false