apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default
  source:
    - repoURL: https://kubernetes.github.io/autoscaler
      chart: cluster-autoscaler
      targetRevision: 9.46.6
      helm:
        valueFiles:
          - $values/dev/cluster-autoscaler/values.yaml
        parameters:
          - name: rbac.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
            value: "arn:aws:iam::773398142927:role/eks-cluster-dev-cluster-autoscaler"
    - repoURL: https://github.com/KHDevOps/eks-scalable-devops-platform
      targetRevision: refacto2
      ref: values
      path: kubernetes/helm-values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false