apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-rbac
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KHDevOps/eks-scalable-devops-platform
    path: kubernetes/platform/rbac/overlays/dev/
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true