apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.12.3
      helm:
        valueFiles:
          - $values/kubernetes/helm-values/dev/ingress-nginx/values.yaml
    - repoURL: https://github.com/KHDevOps/eks-scalable-devops-platform
      targetRevision: refacto2
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true