global:
  securityContext:
    runAsNonRoot: true
    runAsUser: 999
    fsGroup: 999

server:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  
  ingress:
    enabled: false

repoServer:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  
  metrics:
    enabled: true

redis:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  
  metrics:
    enabled: true

applicationSet:
  enabled: true

dex:
  enabled: false