controller:
  serviceAccount:
    create: true
    name: jenkins
rbac:
  create: false
  admin:
    password: "password123"
  installPlugins:
    - kubernetes:4353.vb_47977da_9417
    - workflow-aggregator:608.v67378e9d3db_1
    - git:5.7.0
    - configuration-as-code:1985.vdda_32d0c4ea_b_
    - prometheus:2.0.11
  additionalPlugins: []
  
  additionalVolumes:
    - name: docker-sock
      type: HostPath
      hostPath: /var/run/docker.sock
  
  additionalVolumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
      
  initScripts:
    docker-client.sh: |
      #!/bin/bash
      curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-20.10.9.tgz | tar xzv --strip 1 -C /usr/local/bin docker/docker
      chmod +x /usr/local/bin/docker
  
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

agent:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1024Mi