server:
#  config:
#    url: http://eksargocd.duckdns.org
  
  ingress:
    enabled: false

repoServer:
  metrics:
    enabled: true

redis:
  metrics:
    enabled: true

applicationSet:
  enabled: true

dex:
  enabled: false