controller:
  jenkinsUrl: "http://localhost/jenkins/"
  admin:
    password: "password123"
  env:
    - name: JENKINS_OPTS
      value: "--prefix=/jenkins"

  additionalPlugins:
    - prometheus:2.0.11

  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    ingressClassName: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      kubernetes.io/ingress.class: "nginx"
    paths:
      - path: /jenkins(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
    host: localhost