pipeline {
    agent { label 'built-in' }

    parameters {
        credentials(
            name: 'GIT_CREDENTIALS',
            description: 'Choose your credentials Git',
            credentialType: 'com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl',
            defaultValue: '',
            required: true
        )
    }

    stages {

        stage('Checkout Config Repo') {
            steps {
                git branch: 'main',
                    credentialsId: params.GIT_CREDENTIALS,
                    url: "https://github.com/KHDevOps/eks-scalable-devops-platform"
            }
        }

        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                script {
                    def config = readYaml file: 'templates/app-config.example.yaml'
                    def configRepo = config.git.config_repo
                    def defaultBranch = config.git.default_branch

                    // Créer le contenu du fichier
                    def fileContent = """
        Hello World from Jenkins!

        Build Information:
        - Build Number: ${BUILD_NUMBER}
        - Job Name: ${JOB_NAME}
        - Date: ${new Date()}
        - Branch: ${defaultBranch}

        This is a test deployment!
        """
                    
                    withCredentials([usernamePassword(credentialsId: params.GIT_CREDENTIALS, passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {

                        sh('rm -rf deploy-temp')
                        sh('mkdir deploy-temp')
                        
                        dir('deploy-temp') {

                            sh('git init')
                            sh('git config user.email "jenkins@yourproject.com"')
                            sh('git config user.name "Jenkins Automation"')
                            

                            writeFile file: 'hello-world.txt', text: fileContent
                            
                            sh("git remote add origin https://\${GIT_USERNAME}:\${GIT_PASSWORD}@${configRepo}")
                            sh('git add hello-world.txt')
                            sh('git commit -m "Jenkins deployment"')
                            sh("git push -f origin HEAD:${defaultBranch}")
                        }
                        
                        sh('rm -rf deploy-temp')
                    }

                    echo "Hello World successfully deployed!"
                }
            }
        }
    }   
}