autoDiscovery:
  clusterName: minikube
  enabled: false

cloudProvider: "clusterapi"

extraArgs:
  scan-interval: "30s"
  v: "4"
  logtostderr: "true"
  stderrthreshold: "info"
  leader-elect: "false"
  clusterapi-cloud-config-authoritative: "true"

livenessProbe:
  httpGet:
    path: /health-check
    port: 8085
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

image:
  repository: registry.k8s.io/autoscaling/cluster-autoscaler
  tag: v1.28.0

rbac:
  create: true
  serviceAccount:
    create: true
    name: cluster-autoscaler

resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 50m
    memory: 100Mi

service:
  port: 8085