# Configuration très simple pour tests
cloudProvider: "mock"

extraArgs:
  v: "4"
  logtostderr: "true"
  leader-elect: "false"

# Désactiver la sonde de vivacité
livenessProbe:
  httpGet:
    path: /health-check
    port: 8085
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10

image:
  repository: registry.k8s.io/autoscaling/cluster-autoscaler
  tag: v1.28.0

rbac:
  create: true

resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 50m
    memory: 100Mi