serverFiles:
  alerting_rules.yml:
    groups:
      - name: jenkins.rules
        rules:
          - alert: JenkinsDown
            expr: up{job="jenkins-monitor"} == 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Jenkins is unavailable"
              description: "Jenkins instance has not responded for 5 minutes"
              
          - alert: JenkinsHighCPUUsage
            expr: sum(rate(container_cpu_usage_seconds_total{pod=~"jenkins-.*"}[5m])) / count(container_cpu_usage_seconds_total{pod=~"jenkins-.*"}) * 100 > 80
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage on Jenkins"
              description: "Jenkins has been using more than 80% CPU for 10 minutes"
              
          - alert: JenkinsHighMemoryUsage
            expr: sum(container_memory_working_set_bytes{pod=~"jenkins-.*"}) / sum(container_spec_memory_limit_bytes{pod=~"jenkins-.*"}) * 100 > 80
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage on Jenkins"
              description: "Jenkins has been using more than 80% of allocated memory for 10 minutes"

          - alert: JenkinsHighFailureRate
            expr: sum(increase(jenkins_job_build_failed_total[1h])) / sum(increase(jenkins_job_build_total[1h])) > 0.5
            for: 15m
            labels:
              severity: warning
            annotations:
              summary: "High Jenkins job failure rate"
              description: "More than 50% of Jenkins jobs have failed in the last 15 minutes"

          - alert: JenkinsQueueGrowing
            expr: jenkins_queue_size_value > 10
            for: 15m
            labels:
              severity: warning
            annotations:
              summary: "Jenkins build queue growing"
              description: "More than 10 builds have been queued for over 15 minutes"
              
          - alert: JenkinsPluginFailure
            expr: jenkins_plugins_failed > 0
            for: 10m
            labels:
              severity: warning
            annotations:
              summary: "Jenkins plugin failures"
              description: "One or more Jenkins plugins have failed"
              
          - alert: JenkinsHighHTTP4xxErrorRate
            expr: sum(rate(http_server_requests_seconds_count{job="jenkins", status=~"4.."}[5m])) / sum(rate(http_server_requests_seconds_count{job="jenkins"}[5m])) > 0.2
            for: 15m
            labels:
              severity: warning
            annotations:
              summary: "High rate of HTTP 4xx errors on Jenkins"
              description: "More than 20% of requests to Jenkins are resulting in 4xx errors for 15 minutes"