apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

helmCharts:
  - name: jenkins
    releaseName: jenkins
    repo: "file://../../../helm-charts/jenkins"
    valuesFile: values.yaml