installCRDs: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    prometheusInstance: kube-prometheus
    labels:
      release: prometheus

securityContext:
  enabled: true
  fsGroup: 1001

webhook:
  securePort: 10250
  hostNetwork: false