prometheusOperator:
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false

prometheus:
  prometheusSpec:
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
      runAsGroup: 65534

server:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

alertmanager:
  alertmanagerSpec:
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
      runAsGroup: 65534

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

grafana:
  securityContext:
    runAsNonRoot: true
    runAsUser: 472
    fsGroup: 472
  
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
        
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70
  sidecar:
    dashboards:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
    datasources:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128M