---
- name: Check if applications directory exists
  ansible.builtin.stat:
    path: "{{ argocd_apps_dir }}"
  register: apps_dir_stat
  delegate_to: localhost

- name: List application files
  ansible.builtin.find:
    paths: "{{ argocd_apps_dir }}"
    patterns: "*.yaml"
  register: app_files
  when: apps_dir_stat.stat.exists
  delegate_to: localhost

- name: Apply application configurations
  kubernetes.core.k8s:
    src: "{{ item.path }}"
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ k8s_context }}"
    state: present
  with_items: "{{ app_files.files }}"
  when: apps_dir_stat.stat.exists and app_files.files | length > 0

- name: Display access information
  ansible.builtin.debug:
    msg: 
      - "Argo CD has been installed in namespace {{ argocd_namespace }}"
      - "To access Argo CD UI, run: kubectl port-forward svc/{{ argocd_release_name }}-server -n {{ argocd_namespace }} 8080:443"
      - "Then visit: https://localhost:8080"
      - "Login with username: admin and password shown above"