controller:
  admissionWebhooks:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 190Mi
    limits:
      cpu: 200m
      memory: 250Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  service:
    nodePorts:
      http: 31142
      https: 31080